import {
  AiOutlineArrowDown,
  AiOutlineArrowUp,
  AiOutlineBug,
  AiOutlineCheckCircle,
  AiOutlineClockCircle,
  AiOutlineCloseCircle,
  AiOutlineDollarCircle,
  AiOutlineSafety,
  AiOutlineSetting,
} from 'react-icons/ai';
import {
  BiBug,
  BiCodeCurly,
  BiMinus,
  BiPlus,
  BiSolidBarChartAlt2,
} from 'react-icons/bi';
import {
  BsArrowRightShort,
  BsCaretDownFill,
  BsCaretUpFill,
  BsDashLg,
  BsDiscord,
  BsDot,
  BsExclamation,
  BsExclamationTriangle,
  BsEye,
  BsEyeSlash,
  BsFillLightningChargeFill,
  BsGear,
  BsLightningChargeFill,
  BsLink45Deg,
  BsPlayCircle,
  BsShieldCheck,
  BsStar,
  BsStarFill,
  BsTwitterX,
  BsWallet2,
} from 'react-icons/bs';
import { CgBell } from 'react-icons/cg';
import {
  FaCaretDown,
  FaCircle,
  FaEthereum,
  FaGasPump,
  FaSort,
  FaSortDown,
  FaSortUp,
} from 'react-icons/fa';
import { FaCircleHalfStroke } from 'react-icons/fa6';
import {
  FiCalendar,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiChevronUp,
  FiDownload,
  FiEye,
  FiEyeOff,
  FiGlobe,
  FiLink,
  FiMoreVertical,
  FiTrendingUp,
} from 'react-icons/fi';
import { GoDesktopDownload } from 'react-icons/go';
import { HiArrowsRightLeft, HiOutlineCreditCard } from 'react-icons/hi2';
import { ImShare } from 'react-icons/im';
import {
  MdAccessTime,
  MdAdsClick,
  MdArrowDownward,
  MdArrowOutward,
  MdArrowRightAlt,
  MdArrowUpward,
  MdAssistantNavigation,
  MdBlock,
  MdCheck,
  MdCheckCircle,
  MdCheckCircleOutline,
  MdClose,
  MdContentCopy,
  MdCreditScore,
  MdEdit,
  MdFlag,
  MdFlashOn,
  MdInfoOutline,
  MdLockOpen,
  MdLockOutline,
  MdMenu,
  MdMoneyOffCsred,
  MdOpenInNew,
  MdOutlineCancel,
  MdOutlineCurrencyExchange,
  MdOutlineFindInPage,
  MdOutlineFolderCopy,
  MdOutlineLandscape,
  MdOutlineNotificationsActive,
  MdOutlinePowerOff,
  MdOutlineQuiz,
  MdOutlineRadioButtonUnchecked,
  MdOutlineRefresh,
  MdOutlineStickyNote2,
  MdOutlineSwapHorizontalCircle,
  MdTaskAlt,
  MdUpdate,
} from 'react-icons/md';
import {
  PiArrowDownLeft,
  PiArrowUpRight,
  PiArrowsMergeBold,
  PiCheckBold,
  PiCurrencyCircleDollarBold,
  PiFileText,
  PiMathOperationsBold,
  PiNavigationArrowFill,
  PiPushPin,
  PiPushPinFill,
  PiShuffleSimple,
  PiWalletFill,
  PiXBold,
} from 'react-icons/pi';
import { RiShareForwardFill } from 'react-icons/ri';
import { RxMagnifyingGlass } from 'react-icons/rx';
import { SiFireship } from 'react-icons/si';
import {
  TbActivityHeartbeat,
  TbArrowsCross,
  TbBuildingBridge,
  TbCurrencyDollarOff,
  TbFileDescription,
  TbGenderNeutrois,
  TbTrophy,
} from 'react-icons/tb';

export const Icons = {
  AiOutlineArrowDown,
  AiOutlineArrowUp,
  AiOutlineBug,
  AiOutlineCheckCircle,
  AiOutlineClockCircle,
  AiOutlineCloseCircle,
  AiOutlineDollarCircle,
  AiOutlineSafety,
  AiOutlineSetting,
  BiBug,
  BiCodeCurly,
  BiMinus,
  BiPlus,
  BiSolidBarChartAlt2,
  BsArrowRightShort,
  BsCaretDownFill,
  BsCaretUpFill,
  BsDashLg,
  BsDiscord,
  BsDot,
  BsExclamation,
  BsExclamationTriangle,
  BsEye,
  BsEyeSlash,
  BsFillLightningChargeFill,
  BsGear,
  BsLightningChargeFill,
  BsLink45Deg,
  PiPushPin,
  PiPushPinFill,
  BsPlayCircle,
  BsShieldCheck,
  BsStar,
  BsStarFill,
  BsTwitterX,
  BsWallet2,
  CgBell,
  FaCaretDown,
  FaCircle,
  FaCircleHalfStroke,
  FaEthereum,
  FaGasPump,
  FaSort,
  FaSortDown,
  FaSortUp,
  FiCalendar,
  FiChevronDown,
  FiChevronLeft,
  FiChevronRight,
  FiChevronUp,
  FiDownload,
  FiEye,
  FiEyeOff,
  FiGlobe,
  FiLink,
  FiMoreVertical,
  FiTrendingUp,
  GoDesktopDownload,
  HiArrowsRightLeft,
  HiOutlineCreditCard,
  ImShare,
  MdAccessTime,
  MdAdsClick,
  MdArrowDownward,
  MdArrowOutward,
  MdArrowRightAlt,
  MdArrowUpward,
  MdAssistantNavigation,
  MdBlock,
  MdCheck,
  MdCheckCircle,
  MdCheckCircleOutline,
  MdClose,
  MdContentCopy,
  MdCreditScore,
  MdEdit,
  MdFlag,
  MdFlashOn,
  MdInfoOutline,
  MdLockOpen,
  MdLockOutline,
  MdMenu,
  MdMoneyOffCsred,
  MdOpenInNew,
  MdOutlineCancel,
  MdOutlineCurrencyExchange,
  MdOutlineFindInPage,
  MdOutlineFolderCopy,
  MdOutlineLandscape,
  MdOutlineNotificationsActive,
  MdOutlinePowerOff,
  MdOutlineQuiz,
  MdOutlineRadioButtonUnchecked,
  MdOutlineRefresh,
  MdOutlineStickyNote2,
  MdOutlineSwapHorizontalCircle,
  MdTaskAlt,
  MdUpdate,
  PiArrowDownLeft,
  PiArrowUpRight,
  PiArrowsMergeBold,
  PiCheckBold,
  PiCurrencyCircleDollarBold,
  PiMathOperationsBold,
  PiFileText,
  PiNavigationArrowFill,
  PiShuffleSimple,
  PiWalletFill,
  PiXBold,
  RiShareForwardFill,
  RxMagnifyingGlass,
  SiFireship,
  TbActivityHeartbeat,
  TbArrowsCross,
  TbBuildingBridge,
  TbCurrencyDollarOff,
  TbFileDescription,
  TbGenderNeutrois,
  TbTrophy,
} as const;
