import { ChainEnv } from '@vertex-protocol/client';
import {
  ABSTRACT_PERP_METADATA_BY_PRODUCT_ID,
  ABSTRACT_SPOT_METADATA_BY_PRODUCT_ID,
  ABSTRACT_TESTNET_PERP_METADATA_BY_PRODUCT_ID,
  ABSTRACT_TESTNET_SPOT_METADATA_BY_PRODUCT_ID,
} from './abstract';
import {
  ARB_PERP_METADATA_BY_PRODUCT_ID,
  ARB_SPOT_METADATA_BY_PRODUCT_ID,
  ARB_TESTNET_PERP_METADATA_BY_PRODUCT_ID,
  ARB_TESTNET_SPOT_METADATA_BY_PRODUCT_ID,
} from './arbitrum';
import {
  BASE_PERP_METADATA_BY_PRODUCT_ID,
  BASE_SPOT_METADATA_BY_PRODUCT_ID,
  BASE_TESTNET_PERP_METADATA_BY_PRODUCT_ID,
  BASE_TESTNET_SPOT_METADATA_BY_PRODUCT_ID,
} from './base';
import {
  BLAST_PERP_METADATA_BY_PRODUCT_ID,
  BLAST_SPOT_METADATA_BY_PRODUCT_ID,
  BLAST_TESTNET_PERP_METADATA_BY_PRODUCT_ID,
  BLAST_TESTNET_SPOT_METADATA_BY_PRODUCT_ID,
} from './blast';
import {
  HARDHAT_PERP_METADATA_BY_PRODUCT_ID,
  HARDHAT_SPOT_METADATA_BY_PRODUCT_ID,
} from './local';
import {
  MANTLE_PERP_METADATA_BY_PRODUCT_ID,
  MANTLE_SPOT_METADATA_BY_PRODUCT_ID,
  MANTLE_TESTNET_PERP_METADATA_BY_PRODUCT_ID,
  MANTLE_TESTNET_SPOT_METADATA_BY_PRODUCT_ID,
} from './mantle';
import {
  SEI_PERP_METADATA_BY_PRODUCT_ID,
  SEI_SPOT_METADATA_BY_PRODUCT_ID,
  SEI_TESTNET_PERP_METADATA_BY_PRODUCT_ID,
  SEI_TESTNET_SPOT_METADATA_BY_PRODUCT_ID,
} from './sei';
import {
  SONIC_PERP_METADATA_BY_PRODUCT_ID,
  SONIC_SPOT_METADATA_BY_PRODUCT_ID,
  SONIC_TESTNET_PERP_METADATA_BY_PRODUCT_ID,
  SONIC_TESTNET_SPOT_METADATA_BY_PRODUCT_ID,
} from './sonic';
import { PerpProductMetadata, SpotProductMetadata } from './types';

export const SPOT_METADATA_BY_CHAIN_ENV: Record<
  ChainEnv,
  Record<number, SpotProductMetadata>
> = {
  arbitrum: ARB_SPOT_METADATA_BY_PRODUCT_ID,
  arbitrumTestnet: ARB_TESTNET_SPOT_METADATA_BY_PRODUCT_ID,
  base: BASE_SPOT_METADATA_BY_PRODUCT_ID,
  baseTestnet: BASE_TESTNET_SPOT_METADATA_BY_PRODUCT_ID,
  blast: BLAST_SPOT_METADATA_BY_PRODUCT_ID,
  blastTestnet: BLAST_TESTNET_SPOT_METADATA_BY_PRODUCT_ID,
  mantle: MANTLE_SPOT_METADATA_BY_PRODUCT_ID,
  mantleTestnet: MANTLE_TESTNET_SPOT_METADATA_BY_PRODUCT_ID,
  sei: SEI_SPOT_METADATA_BY_PRODUCT_ID,
  seiTestnet: SEI_TESTNET_SPOT_METADATA_BY_PRODUCT_ID,
  sonic: SONIC_SPOT_METADATA_BY_PRODUCT_ID,
  sonicTestnet: SONIC_TESTNET_SPOT_METADATA_BY_PRODUCT_ID,
  abstract: ABSTRACT_SPOT_METADATA_BY_PRODUCT_ID,
  abstractTestnet: ABSTRACT_TESTNET_SPOT_METADATA_BY_PRODUCT_ID,
  local: HARDHAT_SPOT_METADATA_BY_PRODUCT_ID,
  // Not used
  beraTestnet: {},
};

export const PERP_METADATA_BY_CHAIN_ENV: Record<
  ChainEnv,
  Record<number, PerpProductMetadata>
> = {
  arbitrum: ARB_PERP_METADATA_BY_PRODUCT_ID,
  arbitrumTestnet: ARB_TESTNET_PERP_METADATA_BY_PRODUCT_ID,
  base: BASE_PERP_METADATA_BY_PRODUCT_ID,
  baseTestnet: BASE_TESTNET_PERP_METADATA_BY_PRODUCT_ID,
  blast: BLAST_PERP_METADATA_BY_PRODUCT_ID,
  blastTestnet: BLAST_TESTNET_PERP_METADATA_BY_PRODUCT_ID,
  mantle: MANTLE_PERP_METADATA_BY_PRODUCT_ID,
  mantleTestnet: MANTLE_TESTNET_PERP_METADATA_BY_PRODUCT_ID,
  sei: SEI_PERP_METADATA_BY_PRODUCT_ID,
  seiTestnet: SEI_TESTNET_PERP_METADATA_BY_PRODUCT_ID,
  sonic: SONIC_PERP_METADATA_BY_PRODUCT_ID,
  sonicTestnet: SONIC_TESTNET_PERP_METADATA_BY_PRODUCT_ID,
  abstract: ABSTRACT_PERP_METADATA_BY_PRODUCT_ID,
  abstractTestnet: ABSTRACT_TESTNET_PERP_METADATA_BY_PRODUCT_ID,
  local: HARDHAT_PERP_METADATA_BY_PRODUCT_ID,
  // Not used
  beraTestnet: {},
};
